### ISSUE TITLE
extend list of plugins

### ISSUE THREAD

**Issue by lcd1232** [viasite-ansible/ansible-role-zsh#21]
How to extend list of plugins?
If I add them in .zshrc.local it doesn't affect list of plugins

**Comment by popstas** [comment]
Use `zsh_antigen_bundles_extras` variable in playbook, see example:
``` yaml
- hosts: all
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh
```

**Comment by lcd1232** [comment]
@popstas I tried with playbook and command `sudo ansible-playbook -i "localhost," -c local playbook.yml` but it doesn't work
```yml
- hosts: all
  vars:
    zsh_antigen_bundles_extras:
      - redis-cli
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh
```
In this example I want to add [redis-cli](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#redis-cli) plugin from main repo.

**Comment by popstas** [comment]
Maybe, you want to apply config for current user, but applied it to root.
Check /root/.zshrc for redis-cli presence, if it present, add your user to playbook vars:
``` yaml
- hosts: all
  vars:
    zsh_user: myuser
    zsh_antigen_bundles_extras:
      - redis-cli
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh
```
