### ISSUE TITLE
dnf does not support `cache_valid_time` on `package` (proxy for `ansible.legacy.dnf` on f40)

### ISSUE THREAD

**Issue by rparree** [viasite-ansible/ansible-role-zsh#78]
Hi,

I am getting the following error when using the role on a fedora 40 target machine:

```
fatal: [machine-2-1]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (ansible.legacy.dnf) module: cache_valid_time. Supported parameters include: allow_downgrade, allowerasing, autoremove, best, bugfix, cacheonly, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_repoquery, install_weak_deps, installroot, list, lock_timeout, name, nobest, releasever, security, skip_broken, sslverify, state, update_cache, update_only, use_backend, validate_certs (expire-cache, pkg).'
```

The problem is 

```yaml
- name: Update package cache
  package:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  when: ansible_os_family != 'Darwin'
```

It was recently added: https://github.com/viasite-ansible/ansible-role-zsh/commit/3c6659db86e9c06f72bb7cef94274480676e44b9

I can create pull request
